### ISSUE TITLE
Suggestion: implement command-line help and/or a man page, don't quietly ignore invalid options

### ISSUE THREAD

**Issue by mklement0** [paypal/gnomon#1]
After installation, there is no way to get usage information:
- `gnomon --help` or variations thereof don't work and even invalid options are quietly ignored (which is arguably a bug in itself).
- `man gnomon` doesn't work either.

**Comment by zetlen** [comment]
Excellent suggestion! Fixed in #2 and released in [v1.5.0](https://github.com/paypal/gnomon/releases/tag/v1.5.0).
