### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [paypal/gnomon#7]
Dear @zetlen,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Node?
I’m told that either [Nexe][1] or [EnclosureJS][2] might help you to achieve that.

[1]: https://www.npmjs.com/package/nexe
[2]: http://enclosejs.com/

**Comment by zetlen** [comment]
Hi @sergeevabc, thanks for the suggestion. I've never used either of those, but they seem straightforward; do you think you have the time to add a standalone EXE in a pull request?

**Comment by sergeevabc** [comment]
@zetlen, being a mere user, I would rather entrust compiling binaries to developers.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by zetlen** [comment]
Sorry, I'm a bit swamped right now. I should be able to get to this in the new year!

**Comment by sergeevabc** [comment]
Windows binary is still anticipated.
